name: piggybank
description: The expenses under your control.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.92+6086

environment:
  sdk: '>=2.17.0 <=3.32.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:    # i18n
    sdk: flutter            # i18n
  i18n_extension: ^15.0.5
  i18n_extension_importer: 0.0.6
  sqflite: ^2.4.2
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2 # plugin for persistent store for simple data (key-value pairs) like settings
  community_charts_common: ^1.0.2
  community_charts_flutter: ^1.0.2
  animations: ^2.0.10
  month_picker_dialog: ^6.0.3
  share_plus: ^11.0.0
  flutter_speed_dial: ^7.0.0
  url_launcher: ^6.2.2
  flutter_colorpicker: ^1.0.3
  file_picker: ^10.2.0
  uuid: ^4.2.2
  package_info_plus: ^8.1.1
  flutter_displaymode: ^0.6.0
  future_progress_dialog: ^0.2.1
  csv: ^6.0.0
  encrypt: ^5.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  intl: ^0.20.2
  function_tree: ^0.9.1
  system_theme: ^3.1.2
  flutter_typeahead: ^5.2.0
  file_selector: ^1.0.3
  emoji_picker_flutter: ^4.0.0-dev.2
  reorderable_grid: ^1.0.10
  local_auth: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  test: ^1.24.9
  mockito: ^5.0.17

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/locales/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages